name: iotapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  font_awesome_flutter: ^10.5.0
  video_player: ^2.7.1
  webview_flutter: ^4.2.4
  flutter_inappwebview: ^5.7.2+3
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  audioplayers: ^5.1.0
  flutter_dropdown: ^1.0.1+hotfix.1
  syncfusion_flutter_charts: ^23.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

 